intel/rohd

- lib/src/values/logic_values.dart
Fix issues related to LogicValues value comparison and unary AND and OR
Fix #22
Fix #23
#21 will include tests covering the fixes
No, bug fix only
No
> Fix LogicValues bugs #22 and #23

- README.md
- lib/src/interface.dart
The old `append` argument was limiting in how to rename signals to uniquify them.  A function is more flexible.
Close #6 
Existing interface tests pass.
Yes, `append` is being replaced by `uniquify`.
Yes, API and README updated.
> update connectIO to use uniquify function, close #6

- example/counter.dart
- lib/rohd.dart
- lib/src/logic.dart
- lib/src/modules/clkgen.dart
- lib/src/simulator.dart
- lib/src/utilities/simcompare.dart
- lib/src/values/logic_values.dart
- lib/src/wave_dumper.dart
- test/counter_test.dart
- test/simulator_test.dart
- test/translations_test.dart
- test/wave_dumper_test.dart
Various fixes to the WaveDumper:
- Renamed Dumper to WaveDumper (including a deprecation note)
- Made injection functionality asynchronous so it matches expectations
- Changed `Simulator` timestamps to `int` instead of `double`
- Remove some "boring" signals from what gets dumped by WaveDumper (#5)
- Fix bug where a signal deposition at time 0 after the WaveDumper is attached is not captured (#4)
- Fix WaveDumper functionality so that multiple signal depositions at the same timestamp will take the last one (related to #4)
- Added unit tests for WaveDumper
- Fix some minor documentation typos
Fix #5 
Fix #4
Added new unit tests
Yes
- Simulator timestamps are now int instead of double
- Dumper is deprecated …
> WaveDumper improvements and fixes

- lib/src/logic.dart
- lib/src/modules/conditional.dart
- lib/src/simulator.dart
- lib/src/utilities/simcompare.dart
- test/counter_test.dart
- test/pipeline_test.dart
Various fixes for FF/FlipFlop
- Fix asynchronous flop sampling bugs.
- Improved FF simulation performance by only executing and listening to `Simulator` events when something "interesting" is going on
- Fix `Logic.changed` calculation
- Fix `Simulator.phase` determination
- Add wave dumping option for `SimCompare` iverilog simulations
Fix #41
Close #11
Existing tests cover most things
- Modified counter test to include asynchronous reset
- Modified pipeline test to be more strict on latency
No
No
> Improvements to FF

- analysis_options.yaml
- example/counter.dart
- example/tree.dart
- lib/src/logic.dart
- lib/src/simulator.dart
- lib/src/utilities/synchronous_propagator.dart
- test/example_test.dart
Replaced glitch streams with simple signal propagator objects which are always synchronous.  Makes `put` simpler and purely synchronous, and allows simple reentrance for contention propagation.
N/A
Existing tests cover it
No
Minor API doc updates included
> made signal propagation more robust

- lib/src/interface.dart
- test/counter_wintf_test.dart
Fix #38 so that there aren't exceptions when no tags are provided for one or both of inputTags and outputTags.
#38
Added a line with no tags to an existing interface test
No
No
> Fix #38: `Interface.connectIO` bug with no tags specified

- lib/src/interface.dart
- test/interface_test.dart
- Fix #59 
- Add unit tests for `Interface`
- Improve API docs and comments
#59
Added new unit test and existing unit tests pass
No
No, but updated some documentation
> Fix uniquified `Interface.getPorts` bug, add tests, and improve documentation

- lib/src/values/logic_values.dart
Where possible, converted some `LogicValues` constructors to `const` to improve the performance.
N/A
Existing test suite passes
No
No
> Make some `LogicValues` types `const` for performance

- README.md
- example/example.dart
- lib/src/modules/conditional.dart
- lib/src/modules/pipeline.dart
- lib/src/utilities/simcompare.dart
- test/conditionals_test.dart
- test/counter_test.dart
- test/counter_wintf_test.dart
- test/translations_test.dart
- Rename `FF` to `Sequential`, since it's a better name.
- Add `Sequential.multi` for multiple triggers on one block (like `always_ff(@posedge clk or @posedge reset)`)
Implements a solution for #42 
Modified a counter test to take advantage of `Sequential.multi`
Yes
- The `clk` has been removed from the `Sequential` public API since it probably shouldn't have been exposed in the first place.
- `FF` has been deprecated, but not removed yet, to preserve backwards compatibility.
Yes, API docs are updated
> `Sequential` and `Sequential.multi`

- lib/src/interface.dart
- lib/src/modules/conditional.dart
- lib/src/utilities/simcompare.dart
Modified some `Iterable.forEach` loops into `for(... in ...)` loops which tend to be easier to debug.
N/A
Existing tests pass
No
No
> Convert forEach loops to make debug easier

- README.md
- lib/rohd.dart
- lib/src/modules/bus.dart
- lib/src/swizzle.dart
- test/conditionals_test.dart
- test/swizzle_test.dart
Deprecated the globally visible `swizzle` and `rswizzle` functions and replaced them with extensions on `List` of certain types so that multiple different types of things can be swizzled.  Types include `Logic` (already supported) as well as `LogicValue` and `LogicValues` so that they can be swizzled directly.
#70 
Added new tests for `LogicValue` and `LogicValues` swizzling.  Existing tests were updated to properly cover `Logic` swizzling.
No, but some functions are deprecated
- API docs via comments are updated
- Deprecated decorator is added where appropriate
- Updated README portions that mention swizzling
> modified swizzle functionality and added capability to values

- CONTRIBUTING.md
- README.md
- lib/src/external.dart
- lib/src/modules/conditional.dart
- lib/src/simulator.dart
- lib/src/synthesizers/systemverilog.dart
- lib/src/utilities/simcompare.dart
- test/changed_test.dart
- test/external_test.dart
- Updated some links to documentation to resolve warnings in `dartdoc`.
- Renamed `ExternalModule` to `ExternalSystemVerilogModule` since it is specifically for SystemVerilog.  Marked `ExternalModule` as deprecated.
- Made `topModuleName` a named parameter (required) to reduce confusion when extending `ExternalSystemVerilogModule`.
- Renamed `SimulatorPhase.clksStable` to `SimulatorPhase.clkStable` for consistency.
- Added `simulationHasEnded` to `Simulator`.
- Modified `Simulator` to allow for injected actions to return `Future`s which will be `await`ed.
- Fixed bug where `Simulator` warning about maximum simulation time when not appropriate.
- Fixed a bug where SystemVerilog synthesizer could enter infinite recursion from `ExternalSystemVerilogModule`
- Improved `SimCompare` checking to …
> "External" module updates

- lib/src/modules/conditional.dart
- test/changed_test.dart
Thought of a test case that might not have been covered by other tests related to simulator behavior when injecting on a flop's clock.  This test helps ensure functionality is consistent and doesn't break in the future.
N/A
Added a new test
No
No
> Added a new test for injection on flop clocks

- lib/src/modules/conditional.dart
- lib/src/utilities/sanitizer.dart
- test/changed_test.dart
- test/sequential_test.dart
Fixed a bug related to `Sequential` sampling, where under certain scenarios signals would pass through instead of being flopped.
#79 
Added a new test based on the code sample from #79.  Thank you to @wswongat!
No
No
> Fixed #79 bug related to `Sequential` sampling

- .github/workflows/docs.yml
- README.md
- example/example.dart
- lib/src/logic.dart
- lib/src/modules/bus.dart
- lib/src/simulator.dart
- lib/src/swizzle.dart
- lib/src/values/logic_value.dart
- lib/src/values/logic_values.dart
- test/conditionals_test.dart
- test/logic_values_test.dart
- test/swizzle_test.dart
- test/wave_dumper_test.dart
- Follow `of` vs `from` Dart conventions for `LogicValue` and `LogicValues` (#72); deprecated the old `from` ones.
- Make `LogicValues` creation more flexible between ints and BigInts where possible
- Clarify Simulator misuse by adding a new exception
- Fix test that generated extraneous vcd file
Fix #72 
Added a test and modified a test for flexibility changes.  Updated existing tests to use new API.
No, just deprecation
Yes, updated doc comments and README where necessary
> Replace from with of, plus a couple small fixes

- lib/src/module.dart
- test/trace_bounce_test.dart
- test/trace_test.dart
- Fixes a bug (#84) where in certain scenarios with an output depending on an output of the same module the hierarchy failed to be determined.
- Added a check against inputs depending on other inputs
Fix #84 
- Added new tests that reproduce #84 and confirm the fix
- Added a new test for the new input check to ensure the `Exception` was hit
- Existing test suite protects old functionality
No
No
> Module hierarchy tracing fixes

- README.md
- lib/src/external.dart
- lib/src/logic.dart
- lib/src/module.dart
- lib/src/synthesizers/synth_builder.dart
- lib/src/synthesizers/systemverilog.dart
- lib/src/values/logic_values.dart
- test/name_test.dart
- There are some situations where it is desirable for `Module` instance names to be fixed and not uniquified.  A new flag in `Module` provides the ability to prevent an instance name from being uniquified.
- There are some situations where it is desirable for `Module` definition names to be set in generated output.  A new `String` parameter enables users to specify the desired definition name.  It can be reserved as well via flag, similar to the new capability for instance names.
N/A
Added new tests for new capabilities.
No
API doc comments updated
> Provide the ability to reserve instance names and provide + reserve definition names

- lib/src/synthesizers/systemverilog.dart
- lib/src/values/logic_values.dart
- test/logic_values_test.dart
- test/swizzle_test.dart
Fix #89 which caused `Const`s in `swizzle`s to break in generated SystemVerilog.
#89 
Added a new test which fails without this fix.
No, but it does change the way SystemVerilog gets printed for constants.
No
> Add explicit width to Const generated SystemVerilog

- CHANGELOG.md
- README.md
- lib/src/logic.dart
- lib/src/modules/bus.dart
- lib/src/modules/conditional.dart
- lib/src/values/logic_value.dart
- lib/src/values/values.dart
- run_coverage.sh
- test/bus_test.dart
- test/conditionals_test.dart
- test/extend_test.dart
- test/logic_value_test.dart
- test/swizzle_test.dart
Further improving the usability of and consistency between `Logic` and `LogicValue`.  Includes:
- `getRange` on `Logic`
- `zeroExtend`, and `signExtend` on `Logic` and `LogicValue`, plus `extend` on `LogicValue.
- `withSet` for `LogicValue` and `Logic`
- `reversed` on `Logic`
- `slice` on `LogicValue`
- Reverse slicing on both `Logic` and `LogicValue`
- Made `IfBlock` a little more flexible
- Improved documentation and README around these features
- Added a script to generate line coverage
Close #113
Improve on #91
Close #117
Close #101
Close #83
Fix #122
Passing existing tests and added a bunch more tests.
No
Yes, …
> Various features and testing for `Logic` and `LogicValue`

- lib/src/wave_dumper.dart
- test/wave_dumper_test.dart
Fix a bug where multi-bit values don't properly dump into VCDs by the `WaveDumper`.
Fix #129 
Added new tests to cover this scenario.
No
No
> Fix #129, waveform dump bug for multi-bit values

- lib/src/simulator.dart
- test/simulator_test.dart
Simulator Bug found causing failures 
Fix #126 
Added a new test to reproduce the issue
No
No
> Fix for issue #126 Simulator reset does not wait for simulation to complete and test to reproduce the issue

- README.md
- lib/src/logic.dart
- lib/src/modules/gates.dart
- lib/src/values/logic_value.dart
- test/logic_value_test.dart
- test/math_test.dart
Add modulo support
[](https://github.com/intel/rohd/issues/16)
NO
Yes
> add modulo support

- lib/src/simulator.dart
- test/simulator_test.dart
Make it possible to register actions to be executed at the end of the simulation.  This is useful for "finalizing" lots of things like file IO, checking, etc. at the end of a simulation.
N/A
Added new unit tests.
No
Updated doc comments
> Added actions to execute at the end of the simulation

- lib/src/wave_dumper.dart
The `writeAsStringSync` function causes the rest of the program/simulation to block waiting for file I/O, which can cause simulation slow-down.  Changing the waveform dumper to asynchronously dump through an `IOSink` will improve the simulation performance when doing waveform dumping.
Fix #3 
Existing tests cover dumper functionality to ensure that nothing broke.
No.
Not needed
> Moved wave dump file writing to be async for performance

- lib/src/modules/bus.dart
- test/bus_test.dart
Fix bug related to generated SystemVerilog for bit-slicing on expressions.
Fix #163
Added a new test which fails without this fix.
No.
No.
> Fix #163 - invalid generated SystemVerilog for bit slicing on expressions

- lib/src/synthesizers/systemverilog.dart
- lib/src/utilities/simcompare.dart
- test/assignment_test.dart
Fix an issue related to constant collapsing in generated SystemVerilog.
Fix #159 
Added a new test, based on bug report in #159 from @chykon
No
No
> fix constant collapsing, fix #159

- lib/src/modules/bus.dart
- lib/src/modules/conditional.dart
- test/comb_math_test.dart
- test/comb_mod_test.dart
- test/swizzle_test.dart
Previously, ROHD's `Combinational` would look at direct input changes for its sensitivity list.  There are some cases where changes during execution of the contents of a `Combinational` would have had additional changes onto direct inputs of the `Combinational`, meaning that it should be sensitive to those inputs as well.  This PR includes fixes so that `Combinational` during `build` will find the full sensitivity list by searching for inputs potentially affected by outputs of itself.
Thank you to @chykon for finding the bug (#158) that led to this fix.
Some other bugs were filed and fixed during debug of this issue, including (#163).  This PR also includes a change to how `swizzle` executes in order to properly handle intermediate contention and constants given the increased sensitivity …
> Fix `Combinational` sensitivity detection - Issue #158

- benchmark/BENCHMARKING.md
- benchmark/benchmark.dart
- benchmark/benchmarks.dart
- benchmark/pipeline_benchmark.dart
- lib/src/modules/conditional.dart
- lib/src/utilities/simcompare.dart
- pubspec.yaml
- test/benchmark_test.dart
Improve the performance of `Combinational`'s `_execute` function so that it doesn't glitch extra `x`'s throughout the design unnecessarily.  For some designs this can provide a very meaningful performance boost to simulation speed.
Fix #106 
Existing tests cover this.
Added new benchmarking code that covers a little bit of combinational logic via a pipeline example.
No
No
> Improve performance of Combinational execute

- test/bus_test.dart
During development/debug, a `dontDeleteTmpFiles` was included on one of the tests which makes tests keep some temporary files around even when they pass.  This shouldn't be there.
N/A
Existing tests pass.
No
No
> Remove accidental `dontDeleteTmpFiles` for a bus test

- README.md
The changed name in the workflows caused the badges in the README to break, so fixing those.
N/A
Checked in preview and fork that links look good now.
No
No
> Fix badges in readme after workflow changes

- example/example.dart
- example/fir_filter.dart
- lib/src/external.dart
- lib/src/modules/bus.dart
- lib/src/modules/clkgen.dart
- lib/src/modules/conditional.dart
- lib/src/modules/gates.dart
- lib/src/modules/pipeline.dart
- lib/src/values/small_logic_value.dart
- pubspec.yaml
- test/fsm_test.dart
- test/sequential_test.dart
ROHD currently uses Dart version [2.14](https://github.com/intel/rohd/blob/6ec7ec56744c94e42d7011952fa3391bde031180/pubspec.yaml#L10). It is proposed to upgrade the version to the latest actual - [2.18](https://dart.dev/guides/language/evolution#dart-218). Among the changes, I would especially like to highlight the `super parameters` added in [2.17](https://dart.dev/guides/language/evolution#dart-217), which allow writing more compact constructors.
It also becomes possible to use `enhanced enums`, the idea of using which was mentioned here - #124.
After the version upgrade, it was necessary to use a `dart fix` to apply the recommendations related to the new language features.
No.
After the changes, testing was launched, which was successfully completed.
> Is this a breaking change that …
> Increase Dart SDK version

- lib/src/values/logic_value.dart
- test/logic_value_test.dart
Fixes a bug in parsing large unsigned binary integers (#183)
Fix #183 
Added a new test.  Existing tests pass.
No
No
> Fix #183, parsing of unsigned large binary integers

- README.md
- lib/src/external.dart
- test/external_test.dart
It's inconsistent and confusing to call it `topModuleName`, so rename it to `definitionName`.
Fix #169
Existing tests pass
*Yes!*  This is an API change.  Users will need to change the name of the parameter used.
Yes, updated API docs and README.
> Rename `topModuleName` to `definitionName` in `ExternalSystemVerilogModule`

- README.md
- example/tree.dart
- lib/src/logic.dart
- lib/src/modules/gates.dart
- lib/src/modules/passthrough.dart
- lib/src/modules/pipeline.dart
- test/gate_test.dart
- test/multimodule3_test.dart
- test/multimodule4_test.dart
- test/tree_test.dart
Make the naming of gates better and also make it easier to use a mux.
FIx #135
Fix #13 
Existing tests cover it.
**Yes!**  This changes port names and removes input port visibility (which should have been hidden anyways).
Added deprecation notes, updated API documentation, added a line to README.  Updated README version of `NotGate`.
> Clean up names for ports

- lib/src/module.dart
- lib/src/synthesizers/systemverilog.dart
- test/multimodule5_test.dart
- test/name_test.dart
- Fixed a bug where signal names and module instance names could conflict.
- Fixed a bug where in some cases modules might not be properly detected as sub-modules.
Fix #205 
- Added a new test to cover the sub-module bug
- Added a new suite of tests covering combinations of names for input ports, output ports, internal signals, internal module instance names, internal module definition names, containing module definition names, and containing module instance names
No
No
> Fix bugs related to module naming and instantiation

- lib/src/logic.dart
- lib/src/modules/gates.dart
- test/math_test.dart
Most math operations supported a `dynamic` type to be operated on a `Logic`, but modulo and shift operations (`%`, `>>`, `<<`, `>>>`) only accepted other `Logic`s, which was inconvenient because it requires creating of a `Const` to use them.
This change allows `dynamic` on all these operations as well.
This also closes a testing hole around shift operations.
Close #170 via testing the fix that has been in there since #174
Added tests for all new functionality, as well as missing tests around shift operations
No, this loosens the API but is completely backwards compatible
No
> Allow constants for modulo and shift operations on `Logic`

- test/math_test.dart
Typo in #208, `aModuleConst` -> `aModuloConst`
None
Fixed existing test, functionally the same
No
No
> Fix typo on modulo test

- lib/src/logic.dart
- lib/src/modules/conditional.dart
- lib/src/utilities/synchronous_propagator.dart
- test/changed_test.dart
- test/counter_test.dart
- test/long_chain_test.dart
Refactored `Logic` to hold its value on a `_Wire` which can be shared across many `Logic`s that are connected to each other.  This has two big benefits:
- Improved simulation performance by reducing the number of `glitch`es that need to propagate during combinational logic
- Decreases the stack requirements to help mitigate this issue: #194
Helps mitigate #194
- Added new tests where corner cases could have been introduced around combinational logic propagation and edge listening.
- Ran the (limited) existing benchmark suite and observed slight performance improvement.  The existing pipeline benchmark is not sufficient probably to show the true benefit for larger designs, though.
Sort of, `posedge` and …
> `_Wire`s underneath `Logic`s

- analysis_options.yaml
- lib/src/values/big_logic_value.dart
- lib/src/values/logic_value.dart
- test/logic_value_test.dart
- Fix issues described in #212
- Add extension with utility on BigInt for unsigned conversion
Fix #212
Added new tests covering changes
No
No
> Fix bugs related to 64-bit int conversion, fix #212

- lib/src/modules/conditional.dart
- test/conditionals_test.dart
The default implementation for If, Iff, etc. take lists of Conditionals as inputs, which can be excessively verbose in cases where there is only one Conditional. Adding a special constructor (e.g. something like Iff.s) which takes a single Conditional could make simple code look cleaner.
Issue #12 
Added a new unit test that should return ``true`` if single conditional constructor is used.
Nope.
Yes.
> [Issue-12] simpler constructor of simple control blocks

- lib/src/modules/pipeline.dart
- lib/src/utilities/simcompare.dart
Saw some awkward code, wanted to cleanup
None
Existing tests should valid correctness of this code.
Completely backwards compatible
No need.
> Replace awkward map+reduce chain with smart literal

- benchmark/benchmark.dart
- benchmark/benchmarks.dart
- benchmark/byte_enable_benchmark.dart
- benchmark/logic_value_of_benchmark.dart
- lib/src/modules/bus.dart
- lib/src/values/big_logic_value.dart
- lib/src/values/filled_logic_value.dart
- lib/src/values/logic_value.dart
- lib/src/values/small_logic_value.dart
- lib/src/values/values.dart
- test/benchmark_test.dart
- test/logic_value_test.dart
- test/swizzle_test.dart
String manipulation is not ideal for performance but was used in a number of places for `LogicValue` operations.  This PR removes some of those places where possible.
See conversation that initiated some of these changes here: https://github.com/intel/rohd/pull/213#discussion_r1037443152
This PR specifically fixes:
- Conversion to unsigned `int` from `BigInt` to not use `String`
- `LogicValue.of` to not use `String` (which also optimizes all of the `swizzle` operations on `LogicValue`)
Fixed #202 (since it was convenient for implementation)
Improved upon fixes in #213
Added new tests to cover potential corner cases
No
> Does the change require any updates to documentation?  If so, where?  Are they …
> Optimize LogicValue operations to avoid Strings where possible

- lib/src/logic.dart
- test/changed_test.dart
A bug was introduced in #199 where connecting two `Logic`s together wouldn't propagate signals downstream at connection time if the values were different.  This PR fixes the issue by propagating the change downstream to listeners upon connection.
N/A
Added a simple new test that failed without the fix, based on original bug report
No
No
> Fix bug related to late connection signal prop with wires

- test/changed_test.dart
During some debug, there was some concern on whether ROHD was properly injecting at the right simulation time when triggered on another signal's edge.  This test confirms that ROHD is working properly.  No bug found, but it's good to check in this test to help protect the functionality.
N/A
Only new test added, no functionality changed
No
No
> Added test for changed triggers on injection from changed

- lib/src/modules/conditional.dart
- test/conditionals_test.dart
https://github.com/intel/rohd/pull/210 implements If.s, Iff.s, and ElseIf.s, but not Else.s.
Fix #225 
Add new unit test for single conditionals else then.
No.
No.
> [Issue-225] Add Else.s() constructor to for single then execution

- lib/src/exceptions/conditionals/signal_redriven_exception.dart
- lib/src/exceptions/exceptions.dart
- lib/src/exceptions/module/module_exceptions.dart
- lib/src/exceptions/module/module_not_built_exception.dart
- lib/src/exceptions/name/invalid_reserved_name_exception.dart
- lib/src/exceptions/name/null_reserved_name_exception.dart
- lib/src/exceptions/rohd_exception.dart
- lib/src/exceptions/sim_compare/non_supported_type_exception.dart
- lib/src/module.dart
- lib/src/modules/bus.dart
- lib/src/modules/conditional.dart
- lib/src/modules/gates.dart
- test/comb_sensitivity_search_test.dart
- test/comb_sensitivity_test.dart
Issue #233 finds that searches for `Combinational` sensitivity lists, it is excessively pessimistic in that sometimes there aren't really any combinational paths, but it assumes that there may be.  This can cause an issue where a false combinational loop is detected, causing incorrect X-generation.
This PR fixes the bug by calculating more detailed combinational paths for `Module`s at `build` time.  This information can be leveraged by `Combinational` to understand more accurately where combinational paths may exist.  Results are cached to avoid repeated calculations when multiple `Combinational`s search through similar paths of potential sensitivities.  All `Module`s with custom functionality must explicitly define any combinational paths from all inputs to applicable outputs or else …
> Fix combinational sensitivity excessive pessimism, fix #233

- lib/src/utilities/vcd_parser.dart
- test/wave_dumper_test.dart
The VCD parser is a useful utility for testing, so it's nice to have it as a separate utility rather than just a part of the test.
N/A
Existing tests pass
No
No, but doc comments updated even though non-public API
> Move VCD parser for tests into utilities

- README.md
When `Logic.valueInt` and `Logic.valueBigInt` were deprecated, forgot to update the README.  This PR updates the README.
N/A
Doc update only
No
Doc update only
> Fix README on accessing `int`/`BigInt` values of `Logic`

- lib/src/exceptions/exceptions.dart
- lib/src/exceptions/logic/logic_exceptions.dart
- lib/src/exceptions/logic/put_exception.dart
- lib/src/logic.dart
- test/bus_test.dart
- test/math_test.dart
The exceptions raised by `Logic.put` don't communicate what signal was having an issue, just what the issue was.  This PR adds the name of the signal and makes all `put` exceptions of type `PutException`.
N/A
Added one new test that `PutException` is thrown when there's a width mismatch.  There could be more testing added across other exceptions as part of coverage closure.
No
No
> Improve exceptions for `Logic.put`

- benchmark/benchmark.dart
- benchmark/wave_dump_benchmark.dart
- lib/src/wave_dumper.dart
- test/benchmark_test.dart
- test/config_test.dart
- test/wave_dumper_test.dart
Dumping waves is too slow for large designs on long simulations!  A lot of time was spent in File IO.  This PR makes many fewer file operations by buffering it in a `StringBuffer` and only sending to the file once it reaches a large amount of data.
Also added a benchmark for the `WaveDumper`.
N/A
New benchmark and existing tests
No, but VCD contents will update less frequently now
No
> `WaveDumper` optimization

- lib/src/logic.dart
- lib/src/values/logic_value.dart
- test/bus_test.dart
- test/logic_value_test.dart
It's relatively common to want to grab a bus or value from a certain bit all the way to the end, but right now that requires explicitly specifying the width as the end argument of getRange. It would be nice if supplying only the start would default to grabbing all the way to the end.
Fix #228 
No
> [Issue-228] Make endIndex in getRange an optional positional argument, default to width

- lib/src/values/logic_value.dart
The deprecation suggestion for `IndexError` to use `IndexError.withLength` instead is not backwards-compatible before dart v2.19.  This change alone is not sufficient to justify raising the SDK requirements for ROHD to 2.19, so reverting back with an "ignore" for this lint violation.
N/A
Existing tests and analysis
No
No
> Revert IndexError deprecation change to maintain backwards compatibility

- lib/src/interface.dart
- test/interface_test.dart
When creating a Port, the expectation is that the name will not change. Since Port extends from Logic, and Logic was updated to prevent names from being unsanitary by renaming them using the Sanitizer, it is now possible that the name will be sanitized silently, leading to bugs down the line.
Usually, it's not a good idea to name a port an unsanitary name ever, but sometimes it makes sense to want to name it something unsanitary if you know it will always be uniquified such that it will not actually be unsanitary on an interface.
Fix #234 
> [Issue-234] Port should validate that names are sanitary

- lib/src/modules/conditional.dart
- lib/src/simulator.dart
- test/simulator_test.dart
End of simulation and injected actions are `await`ed in the `Simulator` already, but when you register an action with `Simulator.registerAction` the function is not `await`ed.  This PR makes it more consistent by `await`ing actions registered that way as well.
The implementation revealed that additional error handling was needed in some scenarios for `Sequential`s, as well.
N/A
Added new tests which cover this behavior and adjusted tests which needed it.
It is somewhat of a different behavior than was previously there, but the inconsistency makes this change closer to a bug fix than a new feature or API change.  It may break code that relied on `Simulator.registerAction` not `await`ing in the `Simulator`. …
> `await` registered actions in `Simulator`

- test/logic_name_test.dart
Added function to validate sanitizer
https://github.com/intel/rohd/issues/152
Call sanitizer to check on signal given
No
No
> Added test to check sanitized names

- lib/src/utilities/vcd_parser.dart
- test/example_icarus_waves.vcd
- test/vcd_parser_test.dart
While ROHD generates relatively simple VCD files, other tools (like Icarus Verilog) take advantage of more features of VCD files.  This PR upgrades the `VcdParser` utility in ROHD so that it can check a wider variety of VCD files.  It's still pretty limited, but this helps.
N/A
Added a new test on a VCD file generated by Icarus Verilog
No
No
> Upgrade VcdParser to handle more VCD files

- .github/configs/mlc_config.json
- .github/workflows/general.yml
Since the ROHD project uses `Markdown` for writing documentation and tutorials, it would be nice to make things easier to work with. One of them is link checking. As evidence of the urgency of the problem, you can refer here:
1. https://github.com/intel/rohd/pull/221#discussion_r1097825483
2. https://github.com/intel/rohd/pull/266#discussion_r1104862385
The proposed changes will completely solve the problem from the first point and mitigate the problem from the second point.
The changes themselves are:
* Add a new step to `CI`, during which a link health check will be performed.
* Add a configuration file, in particular allowing to overcome false positives.
The risks of adding a new [action](https://github.com/gaurav-nelson/github-action-markdown-link-check) are minimal as it is executed …
> Add check for Markdown links in CI

- .devcontainer/devcontainer.json
- .gitignore
- .vscode/extensions.json
**DEPENDS ON <https://github.com/intel/rohd/pull/277>**
**RELATED TO <https://github.com/intel/rohd/pull/280>**
It is suggested to add the [extension](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) for VSCode to the list of those installed in the container (`./devcontainer/devcontainer.json`) and the list of recommended ones (`.vscode/extensions.json`). The extension should make it easier to follow the established rules when working with Markdown.
No.
Clone branch, open in VSCode, get suggestions for installing extensions.
No.
This can be mentioned, for example, in `README.md`, but …
> Add `markdownlint` extension

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- SECURITY.md
- benchmark/BENCHMARKING.md
- doc/Architecture.md
- doc/TreeExample.md
- doc/tutorials/Chapter_1/00-Introduction_to_ROHD.md
- doc/tutorials/Chapter_1/01-Setup_Installation.md
- doc/tutorials/Content_Page.md
Markdown files have been formatted. This is to resolve CI errors preventing changes to <https://github.com/intel/rohd/pull/280> from being accepted.
No.
Format testing will be available after accepting changes in <https://github.com/intel/rohd/pull/280>.
No.
Most of the Markdown files are edited, many of which are part of the documentation.
> Format Markdown files

- .github/workflows/general.yml
- .markdownlint-cli2.jsonc
**RELATED TO <https://github.com/intel/rohd/pull/279>**
The motivation for the proposed changes is to make it easier to write collaboratively Markdown.
It is proposed to add a [new step](https://github.com/DavidAnson/markdownlint-cli2-action) to CI to allow parsing Markdown files for formatting issues or deprecated features that may not be handled correctly by some parsers.
Additionally, it is proposed (https://github.com/intel/rohd/pull/279) to add an extension that will allow you to correct errors when working with Markdown in an interactive form and in real time.
---
**ISSUES**
[Run](https://github.com/chykon/rohd/actions/runs/4217962760/jobs/7322121795) revealed a large number of errors. Most can be fixed automatically (eg `MD034/no-bare-urls`), but some require tweaking (eg string …
> Add Markdown linting to CI

- .gitignore
- example/example.dart
- example/fir_filter.dart
- example/tree.dart
Examples should be given special attention, as the quality of the examples can both attract and repel new users from the project.
This set of changes proposes:
* Remove `ignore_for_file: avoid_print` from examples, import `dart:io` and use `stdout.writeln('string')` instead of `print('string')`. Subjectively, ignoring the rules of the linter in the examples does not look very nice.
* Ignore `*.sv` files, because the `fir_filter.dart` example creates a `rtl.sv` file (maybe in the future there will be more examples that save the generated SystemVerilog to a file).
* Slightly tweak comments to match [Effective Dart](https://dart.dev/guides/language/effective-dart/documentation#comments) (dots, capital letters, etc).
* In the `fir_filter.dart` file, the declaration code and comments have been …
> Slightly fix the example files

- .github/workflows/general.yml
It is proposed to slightly edit the CI/CD configuration file, namely:
* Remove hard link to beta as [new stable](https://github.com/gaurav-nelson/github-action-markdown-link-check/releases/tag/1.0.15) is available for step `gaurav-nelson/github-action-markdown-link-check`.
* Add clarification regarding the reason for using the `use-quiet-mode` option in the `gaurav-nelson/github-action-markdown-link-check` step.
* In `deploy-documentation` job, use `ubuntu-22.04` instead of `ubuntu-latest`. Major updates are best done manually.
No.
No.
No.
No.
> Small set of CI/CD configuration changes

- example/oven_fsm.dart
Hide the print statement of LED stream if noPrint is true. 
Fix #300 
no print when run `dart test`.
Nope.
Nope.
> Added no print to the register time

- lib/src/modules/gates.dart
- test/arithmetic_shift_right_test.dart
Shift-right arithmetic (SRA) is broken in generated SystemVerilog if an unsigned operation is applied to the result (see #295)
This fix maintains that the SystemVerilog still uses `>>>` so that it is similar to the original implementation but adds an additional set of `{}` around the result to guarantee safety.
Thank you to @saw235 for the implementation suggestion in https://github.com/intel/rohd/issues/295#issuecomment-1454651572
Fix #295
Added a new test that failed before the fix.
No
No
> Fix #295, signed arithmetic shift right

- lib/src/values/logic_value.dart
- test/fsm_test.dart
There are some comment lines in `logic_value.dart` which are longer than 80 characters.  They were not caught by the lint.  Filed this issue on the linter (https://github.com/dart-lang/linter/issues/4126), but for now just fix these ones.
Also, fixing a race condition in the FSM tests that happened to fail in this PR that had to do with `tmp_test` directory creation.
Linter bug: https://github.com/dart-lang/linter/issues/4126
No, just comment changes, and linter doesn't work.
No
Changes doc slightly since comment was reformatted.
> Fix long comment lines not caught by lint

- lib/src/wave_dumper.dart
- test/wave_dumper_test.dart
These changes fix the issue https://github.com/intel/rohd/issues/324
Fix https://github.com/intel/rohd/issues/324
Added test to check if missing directories can be created.
No.
No.
> [Fix 324] Add `WaveDumper` ability to create missing output directories

- lib/src/synthesizers/synth_builder.dart
- test/synth_builder_test.dart
It's possible to generate outputs using a Synthesizer and SynthBuilder rather than through Module.generateSynth. However, the SynthBuilder does not check that Module.build is called, only generateSynth does. This can produce unexpected outputs (e.g. SystemVerilog with no submodules) without any helpful error message indicating why.
Fix #246 
Tested with module not built and catch exception. 
Yes. 
No. Just added validation and test.
> [Issue 246] SynthBuilder should check for Module.build()

- benchmark/benchmark.dart
- benchmark/comb_guard_fanout_benchmark.dart
- lib/src/collections/iterable_removable_queue.dart
- lib/src/collections/traverseable_collection.dart
- lib/src/module.dart
- lib/src/modules/conditional.dart
- lib/src/synthesizers/systemverilog.dart
- lib/src/utilities/synchronous_propagator.dart
- test/benchmark_test.dart
- test/iterable_removable_queue_test.dart
#344 introduced a performance issue with `SynchronousEmitter` (used in signal `glitch` propagation) when `SynchronousSubscription`s are cancelled.  Removal from a `List` of subscriptions was expensive and in the critical path for simulation performance when there are many `Combinational`s arranged in a particular way.
This PR replaces that `List` with a custom collection called `IterableRemovableQueue` which is optimized specifically for the needs of the `SynchronousEmitter`.  It also includes a benchmark that reproduces the performance issue and tests for the new collection type.
There is still some overhead in having `guard` there at all, but without disabling the check there's not that much I see we can do to improve it.  Moving towards recommending reduced usage of `Combinational` may …
> Optimize `guard` subscription performance in `Combinational` 

- lib/src/modules/conditional.dart
- test/conditionals_test.dart
`Case` and `CaseZ` were not properly using edge-sampled signals for expression evaluation in `Sequentials`.  This PR fixes that bug (#348) and also add tests for both, as well as `If` for good measure.
Fix #348 
Added new tests covering the bug, confirmed failure without the fix.
No
No
> Fix #348: make `Case` and `CaseZ` use edge-sampled signals for expression evaluation

- README.md
- doc/tutorials/chapter_2/00_basic_logic.md
- lib/src/logic.dart
- test/comparison_test.dart
As per #140 , for equality, less than, and less than or equal to, Logic has eq, lt, and lte, respectively, since those operators have different meanings (object equality, conditional assignment, and assignment, respectively). Since greater than and greater than or equal to do not use those operators for something else, they were overloaded for > and >=. However, this is a little inconsistent and confusing to new users. It would be nice if you could also optionally use gt and gte for consistency. 
Added test cases in test/comparison_test.dart 
Yes. I have updated README.md and doc/tutorials/chapter_2/00_basic_logic.md for the support of _gt_ and _gte._
> Issue#140: Added gt and gte for for consistency to Logic

- lib/src/exceptions/conditionals/write_after_read_exception.dart
- lib/src/modules/conditional.dart
Benchmarking, profiling, and usage of recent changes in other designs revealed a few small optimizations that could be made to improve simulation performance when many conditional assignments are used.
- `WriteAfterReadException` no longer prints the signal name.  This enables creating one single `static` function for all write-after-read violations rather than creating a new one during simulation for each signal guarded.  The loss in debug visibility is minimal since signal names going into a `Conditional` are already often not well-named signals, and the full stack trace can provide much more detail.
- Looking up the receiver on each execution of `ConditionalAssign` was redundant overhead, so caching it saves some performance.
N/A
Existing tests cover functionality. …
> Simulation performance improvements for conditional assignments

- lib/src/modules/conditional.dart
- test/flop_test.dart
Currently, to make a flop requires `FlipFlop(clk, d).q`, but it would be nicer to write `flop(clk, d)` to get the same thing as per #257 
Fix #257 
Updated `test/flop_test.dart` with added `flop()`
Yes, need to mention additional `flop()` function support (not included by me).
> Issue#257: Added flop like function to construct FlipFlop

- lib/src/modules/conditional.dart
- test/pipeline_test.dart
- test/ssa_test.dart
In some cases of logic reuse for SSA, there was a scenario where signals could attempt to reconnect to themselves causing false failures.  This PR fixes the bug by skipping over those cases.
This bug was discovered via the integer pipeline multiplier in ROHD-HCL with an updated dependency.
N/A
Added 2 tests:
- one is based on the pipeline code from ROHD-HCL pipelined integer multiplier
- one is a distilled minimal example to reproduce the issue in just SSA
No
No
> Fix bug with SSA reuse of signals

- lib/src/signals/logic.dart
- lib/src/signals/logic_structure.dart
- lib/src/signals/wire.dart
- test/changed_test.dart
- test/previous_value_test.dart
In testbenches, it can be useful to see the "previous" value of a signal before a clock edge when sampling something, e.g. for modelling hardware.  This PR includes a `previousValue` onto `Logic` that shows the value of a signal before the most recent `Simulator.tick`.
N/A
No
API docs yes
> Add `previousValue` to `Logic`

- lib/src/state_machine.dart
- test/fsm_test.dart
Even though the FSM should never allow the case statement to reach an invalid state, synthesis tools may still infer a latch for receivers in the actions which are not assigned in the `default` case.  This PR fixes this issue by zeroing out all receivers mentioned in any actions in the `default`, even though it should never happen.
N/A
Added a test that the zero-out happens.
No
No
> Fix bug where FSM may cause inferred latch

- .github/configs/mlc_config.json
- .github/workflows/general.yml
- CODE_OF_CONDUCT.md
- lib/src/modules/conditional.dart
- test/ssa_test.dart
Sometimes an intermediate SSA signal in a `Combinational` that generates phi signals could be undriven in other clauses (`If` and `Case`).  This is functionally fine since those intermediate signals are unused in the other clauses, however synthesis tools may infer a latch on them.  This also means SV linting tools will flag errors, since the synthesis tool may infer a latch.
This PR sets these unimportant intermediate signals to 0 in unused cases.  It would be better if synthesis tools could be told to treat something as a dont-care instead of 0, but this is the best solution for now without that.
Also, this fixes a bug in `Case` where SSA could be missing a default item, which breaks the phi logic.
Also, this fixes a bug in `If` where an extra empty "else" clause is generated sometimes …
> Fix bugs where SSA could potentially generate inferred latches

- lib/src/modules/conditional.dart
- test/conditionals_test.dart
When multiple cases match on a unique case statement, it currently causes an exception to be thrown. Perhaps this should be a configurable option allowing X's to be driven instead. 
Fix #107
> Unique case with multiple match behavior

- lib/src/interfaces/interface.dart
- lib/src/module.dart
- lib/src/modules/conditional.dart
- lib/src/values/logic_value.dart
- test/flop_test.dart
- test/interface_test.dart
- test/module_test.dart
- test/sequential_test.dart
This PR has a couple things in one:
- "try" ports, where it will return `null` if a port doesn't exist (on a `Module` or an `Interface`)
- Reset (and reset value) on `flop` and `FlipFlop`.
Fix #69
Fix #405
Added tests for new functionality
No
Updated API docs
> Reset for flops and try ports

- lib/src/exceptions/exceptions.dart
- lib/src/exceptions/logic_value/value_width_mismatch_exception.dart
- lib/src/exceptions/sim_compare/non_supported_type_exception.dart
- lib/src/exceptions/unsupported_type_exception.dart
- lib/src/modules/gates.dart
- lib/src/utilities/simcompare.dart
- lib/src/values/big_logic_value.dart
- lib/src/values/filled_logic_value.dart
- lib/src/values/logic_value.dart
- lib/src/values/small_logic_value.dart
- lib/src/values/values.dart
- test/gate_test.dart
- test/logic_value_test.dart
- test/logic_value_width_test.dart
This PR is primarily focused on making sure shifts (left, right, and right arithmetic) perform without error and correctly for any input.  It also includes some additional improvements that are related to fixing this.
- Fix shifting bugs related to signed numbers and numbers that could be interpreted as signed (or not signed)
- Fix shifting of invalid values to properly shift in 0s or Xs rather than assume the whole bus is X
- Add capability to construct a `LogicValue` by inferring the width (using `ofInferWidth`) of positive numbers
- Allow shifting by "huge" amounts to give the right answer (e.g. >width, > max width, > int max)
- Allow `toInt` on LogicValues with big widths but that can be properly represented by an int
- Allow shift of constants to infer the width of non-LogicValue …
> Fixes and improvements related to shifts

- doc/user_guide/_docs/A02-logical_signals.md
- doc/user_guide/_docs/A20-logic-arrays.md
- tool/generate_coverage.sh
- tool/gh_actions/analyze_source.sh
- tool/gh_actions/check_documentation.sh
- tool/gh_actions/check_folder_tmp_test.sh
- tool/gh_actions/generate_documentation.sh
- tool/gh_actions/install_dependencies.sh
- tool/gh_actions/install_iverilog.sh
- tool/gh_actions/run_tests.sh
- tool/gh_actions/verify_formatting.sh
- tool/gh_codespaces/install_dart.sh
- tool/gh_codespaces/run_setup.sh
- tool/run_checks.sh
Clean up some documentation and comments
N/A
Doc only
No
No
> Cleanup some doc and comments

- lib/src/module.dart
- lib/src/modules/conditional.dart
- lib/src/synthesizers/systemverilog.dart
Like other `input`s in `Module`, the `inputs` API should also be marked `@protected` to help prevent accidental usage of input pins outside of its containing `Module`.
N/A
Just static analysis checks
Improper usage may now get some static analysis warnings
No
> Mark inputs as protected in `Module`

- lib/src/synthesizers/systemverilog.dart
- test/sv_gen_test.dart
Sort ports and internal signal declarations alphabetically in generated SystemVerilog.
Fix #395
Added new test that checks it is sorted (confirmed failure without fix).
SV generated will change, but will still be functionally equivalent.
No
> Sort ports and internal signals, fix #395

- lib/src/modules/conditional.dart
- test/conditionals_test.dart
Allow multiple non-blocking assignments in `Sequential`.  See #321.
Added a `allowMultipleAssignments` flag to `Sequential`, defaulting to `true`.
Fix #321 
Updated existing tests for exception, and added new test allowing multiple assignments.
No, but default is now *less* strict
API docs updated
> Allow multiple nonblocking assignments, fix #321

- lib/src/modules/gates.dart
- lib/src/signals/logic.dart
- lib/src/values/logic_value.dart
- test/math_test.dart
Some operations (`+`, `<<`) can cause the output of the operation to be larger than the inputs.  In ROHD, the output width equals the input width (strictly).  The generated SV properly did truncation, but in a way that could flag lint errors due to signal width mismatches.
This change makes it so that we explicitly slice the relevant range rather than rely on SV behavior for signal width mismatch, thus removing lint issues.
Fix #298 
Added a new test that ensures `+` and `<<` use a slice operation.  Don't have an open-source lint tool available for the test suite, but will test it separately to ensure that the fix works properly.
No
> Does the change require any updates to documentation? If so, where? Are …
> Fix bug where generated SV has lint issues with plus and shift-left due to SV width expansion

- CONTRIBUTING.md
- lib/src/module.dart
- lib/src/signals/port.dart
- lib/src/synthesizers/synthesis_result.dart
- test/counter_wintf_test.dart
- test/module_merging_test.dart
- test/tree_test.dart
- tool/gh_actions/generate_documentation.sh
This PR fixes some more naming issues discovered during customer testing after #439.
- Make internal signals use an ordered Set to avoid improper duplication of generated SV module definitions.
- Make `Port` mergeable to avoid calls to `connectIO` from duplicating signal names in generated SV unnecessarily.
- Prevent `reserveDefinitionName` Modules from being merged if they have different definitionNames.
- Disable link validation in dart doc for documentation deployment due to dartdoc bug (https://github.com/dart-lang/dartdoc/issues/3584).
- Update doc link to icarus verilog
Fix #345
Added tests to fix bugs and cover new functionality.
No, though generated SV will change
> Does the change require any …
> More module and signal naming improvements

- lib/src/synthesizers/systemverilog.dart
- test/logic_name_test.dart
Sometimes one may wish to explicitly drive a `Z` (floating) on a signal and have that show up in the generated SystemVerilog (e.g. testbench or behavioral code).  There was an assertion in the SV generation to prevent an accidental `z` from showing up on a floating signal (left undriven).  However, if someone explicitly connects a signal to `Const('z')` (for example) in a way that can't be collapsed away (e.g. in a `mux`), we should just generate with the `Z` in there rather than fail with an assertion.  This does not guarantee that every `Z` in the ROHD side will show up as a `Z` in the SV side, it just enables explicit floating.
N/A
Added a couple tests reproducing issues as reported by a user
No
> Does …
> Allow constant Z driving to show up in SV without error

- benchmark/benchmark.dart
- benchmark/ssa_driver_search_benchmark.dart
- lib/src/modules/conditional.dart
- lib/src/signals/logic.dart
- test/benchmark_test.dart
- test/ssa_test.dart
For sufficiently large and complex designs, a substantial performance penalty was paid for constructing `Combinational.ssa` due to the search algorithm for potential SSA drivers.  The algorithm had to search backwards from inputs to `Conditional`s for potential SSA drivers.  This was especially expensive when using the `Pipeline` abstraction, since that chained multiple `Combinational.ssa`s together.
This PR changes the algorithm to search outwards from SSA drivers to cache signals that are driven by it.  This trades the performance glass jaws:
- originally, if you had much logic defined *before* a `Combinational.ssa`, you could pay a performance penalty proportional to the size of that logic
- now, if you have a substantial amount of unrelated logic connected to an SSA driver (at the …
> Optimize performance of `Combinational.ssa` driver search

- example/example.dart
Some feedback about the counter example has been:
- For newcomers, it is a pretty verbose implementation.
- The example testbench code doesn't expose newcomers to the `await` style.
This PR updates the example to use some `await`s as well as make the counter implementation simpler.  The downside is that it no longer demonstrates `Sequential` in the more general case, but there are other examples and API docs that can be referenced for that.
N/A
Example is covered by test, also rerun locally
No
Basically just doc update
> Update counter example to be simpler and a better reference

- .github/workflows/general.yml
It is safest to put a default permissions in GitHub Actions workflows.
N/A
This PR will test it
No
No
> Update default permissions in GH actions

- lib/src/finite_state_machine.dart
- test/fsm_test.dart
The `defaultNextState` was added to `FiniteStateMachine` but did not show up properly in the mermaid diagrams that were generated.  This PR fixes that.
Also, there was insufficient testing around `defaultNextState`, so this adds testing for it.
N/A
Added a new test
No
No
> Fix defaultNextState diagram generation in FSM

- README.md
- doc/tutorials/chapter_7/answers/exercise_1_d_flip_flop.dart
- doc/tutorials/chapter_7/shift_register.dart
- doc/user_guide/_docs/A01-sample-example.md
- doc/user_guide/_docs/B02-comparisons-with-alternatives.md
- doc/user_guide/_get-started/01-overview.md
- lib/src/finite_state_machine.dart
- lib/src/simulator.dart
- test/fsm_test.dart
- test/simulator_test.dart
Sometimes when ending a simulation, you may want to wait for it to actually end.  This PR makes `Simulator.endSimulation` return a `Future<void>` which is the same as `Simulator.simulationEnded`, saving some time and lines.
N/A
Added new test
Probably not, but you may get a lint warning depending on settings for unawaited futures, or you may get some behavior changes if you have things that behave differently on Futures vs voids.
No
> Make `Simulator.endSimulation` return a `Future`

- lib/src/signals/logic_structure.dart
- lib/src/signals/wire.dart
- lib/src/simulator.dart
- test/changed_test.dart
- test/logic_structure_test.dart
- tool/gh_actions/run_tests.sh
This PR addresses two categories of issues:
- Non-synthesizable (instrumentation) calls to `LogicStructure`s would call `packed` sometimes, which could result in non-functional generation impact and unexpected `null`s in things like `previousValue`.  https://github.com/intel/rohd/issues/457
- The `changed` mechanism in `Logic` did not work properly across `Simulator.reset` calls, so this PR also fixes these issues.  This was discovered during fixes to the first bullet.
Fix #457 
No
No
> Fix bugs in `LogicStructure` instrumentation calls to `packed` and `changed` issues across `Simulator.reset`

- lib/src/modules/gates.dart
- lib/src/signals/logic.dart
- lib/src/signals/logic_structure.dart
- lib/src/values/logic_value.dart
- test/extend_test.dart
- test/gate_test.dart
- test/logic_value_test.dart
It would be useful to be able to calculate the absolute value of a signal or value (convert negative to positive, or leave positive as is).
Fix #360 
> Absolute value

- CHANGELOG.md
- lib/src/module.dart
- lib/src/modules/conditional.dart
- lib/src/synthesizers/synth_builder.dart
- lib/src/synthesizers/systemverilog.dart
- test/conditionals_test.dart
- test/sv_gen_test.dart
Previous changes made any invalid value on a conditional assignment turn the entire bus to `X`, which is very pessimistic, probably too much.  Better would be to convert any `Z` bit to `X`, but leave the valid bits alone.  That's the main change in this PR.
Also:
- Fix some doc comments
- Fix a missing link in CHANGELOG
- Add some assertions to help catch SV generation issues in case users override built-in functionality from `Logic`, `Module`, etc.
- Add a more interesting test on `CustomSystemVerilog` SV generation.
N/A
Added new tests, plus existing tests cover a lot
No, but behavior will be slightly more optimistic now (closer to previous implementation).
> Does the change require any updates to …
> Make conditional assign a little more optimistic with invalid values

- README.md
- doc/tutorials/README.md
Add YouTube link to let audience to find the tutorials easier.
None
None
Yes
No
> Add youtube channel link to Readme.md

- lib/src/simulator.dart
- test/simulator_test.dart
The intention of these changes is to enable Rohme / Rohd interoperability by Layering Rohme on top of the Rohd simulator.
Rohd needs three kinds of callback:
1.  Post to a future time ( Timer( SimDuration(...) , callback )
2.  Post to the next delta ( Timer( SimDuration.zero , callback )
3.  Post to "end of this delta" ( scheduleMicrotask )
Statistically speaking, (1) and (2) are common while (3) is rare.
As a result of (2), one time slot may have many delta cycles. Each time slot looks like this:
delta 0:
- { callbacks originally scheduled for this time slot}
- { microtasks scheduled by callbacks in delta 0}
delta 1:
- { zero time callbacks scheduled in delta 0}
- { micro tasks scheduled by callbacks in delta 1 }
...
delta n:
- { time zero callbacks scheduled by delta n-1 }
- { …
> Simulator upgrades for rohme compatibility (registering now and cancelling)

- lib/src/synthesizers/systemverilog.dart
- test/logic_name_test.dart
In cases where a uniquified array element name (e.g. "ArrayX" element 0 would be "ArrayX_0" internally) collided with actual submodule port names (e.g. a non-array port named "ArrayX_0"), the SystemVerilog generated would misconnect the non-array-element port to an index of the array.  This was because array element names were assumed to be port names if their parent was a port, which is a false assumption.
This PR fixes the bug for both inputs and outputs.  It also adds more robust checking and assertions in the generation to catch any similar issue up-front.
N/A
Added one new test, plus more assertions and safety in the implementation.
No
> Does the change require any updates to documentation? If so, …
> Fix a bug where array port element naming collisions with port names caused misconnections

- .github/workflows/build_devtool.yml
- .github/workflows/general.yml
To test out the unreleased version of the devtool_extension, we can allow github action to commit the build artifact and modified the .gitignore. So, user can point to this package in pubspec.yaml via the use of:
```yaml
rohd:
git:
url: https://github.com/quekyj/rohd.git
ref: artifacts
```
Branch that have the artifact:
- artifacts
Tested on fork.
no
No.
> chore(devtool): build devtool artifact and commit to other branch

- lib/src/simulator.dart
Refactored tick() method in simulator.dart.
The high level motivation is to move towards a common scheduler shared by the Rohd and Rohm simulators. This is preparatory refactoring with that in mind.
Concretely, I have added a method for each phase.
- all phase methods update _phase and add an event to their controller to let listeners know the new phase is now in progress
- some phases are synchronous and not awaited
- other phases are asychronous and are awaited
- the asynchronous phases do something important before or after transitioning to the phase in question
The tick method now looks like this:
```
static Future<void> tick() async {
if (_injectedActions.isNotEmpty) {
_pendingTimestamps.putIfAbsent( _currentTimestamp , () => ListQueue() );
}
// the main event loop
if …
```
>     Refactored tick() in simulator.dart

- .github/workflows/general.yml
Updating to use a new type of self-hosted runner for GitHub actions.  This should help with the slow pick-up of jobs from the GitHub-hosted runners.
This is an experiment until it's proven out sufficiently.
N/A
This is it!
No
No
> Update to use new runners in github actions

- .github/workflows/build_devtool.yml
- .github/workflows/general.yml
Follow-up to https://github.com/intel/rohd/pull/417
A couple things:
- The Intel runners seem to run a little slower than the GitHub ones, so increasing timeouts to allow for it 
- Some jobs didn't have the updated runners, so updating those also
N/A
This PR tests it
No
No
> Adjust CI timeout and runners

- doc/user_guide/_docs/A18-unit-testing.md
- lib/src/exceptions/exceptions.dart
- lib/src/exceptions/simulator_exception.dart
- lib/src/simulator.dart
- test/simulator_test.dart
This improves the exceptions and documentation for when you forget a call to `Simulator.reset()`.
Fix #490
Added a new test
No
Yes, this is basically doc changes only
> Improve simulator timestamp in past errors, suggest reset, fix #490

- analysis_options.yaml
- lib/src/modules/gates.dart
- lib/src/selection.dart
- lib/src/signals/logic.dart
- lib/src/signals/logic_array.dart
- lib/src/utilities/simcompare.dart
- lib/src/values/logic_value.dart
- test/translations_test.dart
A handful of housekeeping things:
- Update the `analysis_options.yaml` with the latest options, enabling what we want to include
- Clean up lint violations, including deprecations from newer versions of libraries (e.g. `collection`)
- Remove a workaround (for https://github.com/dart-lang/sdk/issues/54329) that had disabled some javascript testing
Found one issue in https://github.com/intel/rohd/pull/494, so just fixed a handful more with it.
N/A
PR should cover it
No
No
> Update analysis options, lint cleanup, SDK workaround removal

- lib/src/module.dart
- lib/src/synthesizers/systemverilog.dart
- test/module_test.dart
In certain scenarios, it is possible for internal signals to not be discovered during `Module.build()` when they are connected element-wise to `LogicArray`s and not otherwise connected to other signals or sub-modules.  This should not cause any functional issues in simulation or generated SystemVerilog, but it can affect whether signals are present in the generated outputs or discoverable by querying the `internalSignals` API.  Some tools that leverage ROHD care about these, which was how the bug was discovered.
N/A
Added a new test, existing tests cover functionality
No
No
> Fix bug in internal array discovery during Module build

- lib/src/module.dart
- lib/src/signals/logic.dart
- lib/src/signals/logic_structure.dart
- test/module_test.dart
Similar to the changes in https://github.com/intel/rohd/pull/494, this is an expansion to search properly for potentially undriven or unconventionally connected elements of `LogicArray`s and `LogicStructure`s which could sometimes be missed from being added to `internalSignals`.  This doesn't affect functionality during simulation, and wouldn't really affect generated SystemVerilog either, but the SystemVerilog generation may hit assertions and break assumptions with the missing signals.  It can also make results confusing for anything depending on `internalSignals` APIs.
This PR fixes the issues.
N/A
Add new test + existing tests
No
> Does the change require any updates to documentation? If so, where? Are …
> Fix bug where unconnected array drivers may be omitted incorrectly

- lib/src/synthesizers/systemverilog.dart
- test/sv_param_passthrough_test.dart
This is a bug fix for when parameter arguments in custom-generated SystemVerilog have provided parameter information (either instantiation or definition), but the list/map is empty (but non-null).  It is illegal SystemVerilog syntax to generate something like `#( )`, but that's what was being generated.  The fix is to look for `null` OR empty conditions.
N/A
Added a new test that covers both instantiation and definition empty parameter scenarios.
No
No
> Do not generate SystemVerilog parameter syntax when there are 0 parameters

- lib/src/signals/logic_structure.dart
- test/logic_array_test.dart
The logic which calculated which elements should exist within a call to `slice` or `getRange` in `LogicStructure` generated inaccurate results in some scenarios.  This PR fixes the bug and adds more tests around it.
N/A
Added new tests for corner cases, plus existing tests cover a lot of the existing cases
No
No
> Fix bug in `LogicStructure.getRange` calculations

- doc/user_guide/_docs/A04-assignment.md
- lib/src/signals/logic.dart
- lib/src/signals/logic_array.dart
- lib/src/signals/logic_structure.dart
- test/assignment_test.dart
Adds the `assignSubset` API to `Logic` and `LogicStructure`, with similar semantics as existed for `LogicArray`.
See #500 for details on motivation.
Fix #500 
Added new tests, plus existing tests covered `LogicArray` behavior.
No
Yes, added to user guide and updated API docs
> `Logic.assignSubset` for partial assignments to `Logic`

- lib/src/diagnostics/inspector_service.dart
- lib/src/interfaces/interface.dart
- lib/src/module.dart
- lib/src/signals/logic_structure.dart
- lib/src/synthesizers/systemverilog.dart
- lib/src/utilities/simcompare.dart
- test/interface_test.dart
- test/module_test.dart
Adds new APIs to `Module` to access the original "driver" or "source" when an input or inOut port was created.
See #501 for more information on motivation, etc.
Also, removed the `@protected` on various APIs related to accessing inputs and inOuts on Modules since (a) it wasn't really protecting much during hardware generation since modules could access it without lint warning, and (b) because the proper use and connectivity of the APIs is already dependent on user understanding of in/out rules for module building.
 
Fix #501
Add tests for new APIs + existing tests to make sure nothing broke
Variable name changes from `x` to `source` on port creation APIs may trigger warnings on overrides of those functions, …
> Add `inputSource` and `inOutSource` to `Module`

- lib/src/synthesizers/systemverilog.dart
- test/array_collapsing_test.dart
The checks for collapsing array assignments in generated SystemVerilog had checked that all elements from one array are assigned to all elements of another array.  However, it did not check that the order on the driver matched the order on the receiver.  This means if you did all elements from one array to all elements of another array, but shuffled the order, the assignments would be incorrectly collapsed and the generated SV would be incorrect.
This PR introduces a fix for this bug and adds a test which failed prior to the fix, but now passes.
N/A
Added new test
No
No
> Bug fix: shuffled array assignments incorrectly collapsed in generated SV

- lib/src/utilities/uniquifier.dart
- test/uniquifier_test.dart
The `Uniquifier` in ROHD is useful in many situations, but not exposed as a public API of ROHD (yet?).  Because it is private, the API is a little bit confusing as it relates to reserved items and was also not heavily unit tested.
This PR:
- Adds better testing for the Uniquifier
- Upgrades the `isAvailable` API to properly consider whether a reserved item should be considered available or not
- Optimizes the implementation to be a little more performant, since it is called many times
Related to #134, but not closing it
Added new tests, and existing tests help protect that nothing broke
Only if someone relied on the weird API behavior of an internal utility of ROHD
> Does the change require any updates to …
> Upgrade and improve `Uniquifier` API

- lib/src/module.dart
It is difficult to debug and identify from where (which module) `UnavailableReservedNameException` is getting thrown
Fixes #521 
Added duplicate port names in example files and verified that the exception message includes the module name
NA
NA
> Improved port already exists error message with module name

- .gitignore
- .pubignore
- doc/user_guide/_docs/A11-interfaces.md
- lib/src/interfaces/pair_interface.dart
- test/array_collapsing_test.dart
Some minor doc fixes and tests that have been stacking up in a local area.
- Update some ignores
- Fix some documentation typos
- Add a couple more tests related to array collapsing
N/A
New tests pass, existing tests cover everything
No
That's pretty much all it is
> Doc fixes and a couple more tests

- doc/architecture.md
- doc/user_guide/_docs/A02-logical_signals.md
- lib/src/values/logic_value.dart
- test/logic_value_test.dart
Added LogicValue radix string conversion routines.
None
Added tests that include roundtrip conversions and corner cases.
No.
Yes:  updated the user-guide with an example of conversion.  Documentation in the source can eventually be put in the user-guide.
> RadixString code

- CHANGELOG.md
- doc/user_guide/_get-started/01-overview.md
- example/fir_filter.dart
- example/oven_fsm.dart
- lib/src/exceptions/name/invalid_reserved_name_exception.dart
- lib/src/finite_state_machine.dart
- lib/src/interfaces/interface.dart
- lib/src/modules/conditional.dart
- lib/src/modules/pipeline.dart
- lib/src/simulator.dart
- lib/src/utilities/naming.dart
- lib/src/utilities/simcompare.dart
- lib/src/utilities/vcd_parser.dart
- test/async_reset_test.dart
- test/changed_test.dart
- test/example_test.dart
- test/fsm_test.dart
- test/net_bus_test.dart
- test/pipeline_test.dart
- test/sequential_test.dart
- test/wave_dumper_test.dart
There were a handful of bugs and issues related to asynchronous reset, reset values, simulator injections, waveform dumping, etc.  This PR addresses a variety of those issues.
- Updated examples to be better and compatible with changes
- Improved `InvalidReservedNameException` messages
- Improved error messages when a port does not exist on an interface
- Added `asyncReset` to `Sequential`, `FiniteStateMachine`, `Pipeline`, `FlipFlop`, `flop`
- Make sequentials drive `x` if a trigger and non-trigger happen at the "same time" in a tick to help catch non-synthesizable behavior in designs around flops
- Fixed a bug where a multi-triggered Sequential may not generate X's if one trigger is valid and another (later specified) trigger is invalid.
- Added support for both posedge and negedge …
> Async Reset Improvements

- lib/src/simulator.dart
- test/simulator_test.dart
- tool/gh_actions/run_tests.sh
There were cases where an error could occur during simulation and the simulation would not indicate that it had ended.  This PR fixes those bugs and adds tests to cover those scenarios.
For example:
- A registered action throws
- Something calls `Simulator.throwException`
- An end of simulation action throws
N/A
No
No
> Fix bugs in Simulator error handling and end of simulation

- lib/src/exceptions/logic_value/logic_value_construction_exception.dart
- lib/src/exceptions/logic_value/logic_value_conversion_exception.dart
- lib/src/exceptions/logic_value/logic_value_exceptions.dart
- lib/src/values/logic_value.dart
- test/logic_value_test.dart
Added an option to LogicValue.toRadixString and .ofRadixString to use '_' as a default separator, but allow
for the user to specify a different separator.
#534 
Converted tests to use _ as separator after testing with sepChar argument.
Yes.  Previously output radixStrings will not parse by default as they will have spaces.
Documentation in the class code is now up to date with this change.
> LogicValue radixString uses underscore separators by default

- lib/src/modules/conditionals/combinational.dart
- test/pipeline_test.dart
- test/ssa_test.dart
There was a bug in the way that the `Combinational.ssa` was discovering/notifying signals of drivers when `LogicStructure`s were split apart and rejoined.  This PR fixes that bug by expanding the search to the `parentStructure` signals being searched.  It also expands the search to elements of `LogicStructure`s just in case, even though it appears that wouldn't be a problem.
N/A
Added new tests that reproduce the issue.
No
No
> Fix bug in SSA discovery when `LogicStructure`s are used

- lib/src/exceptions/module/port_rules_violation_exception.dart
- lib/src/module.dart
- lib/src/signals/logic_structure.dart
- test/module_test.dart
This PR has 2 main components:
- A fix for a bug which causes "trace errors" (`PortRulesViolationException`) when a `LogicStructure` contains a port of a `Module`.
- A greatly improved error message for `PortRulesViolationException`s which shows the full stack of signals that led to the exception, which should make it *much* easier to debug these types of issues.
Thank you to @desmonddak for finding this issue during development of https://github.com/intel/rohd-hcl/pull/152
An example of the new format for a tracing error (in this case, a missing `addInput`):
```
Violation of input/output rules in module "missing_input_mod" (MissingInputRegistrationModule)  :  (b) on signal Logic(1): a. Logic within a Module should only communicate outside of itself by consuming inputs/inouts and driving …
```
> Fix bug where `Module.build` didn't follow through structs containing ports properly, plus improved debug messaging.

- lib/src/values/logic_value.dart
- test/logic_value_test.dart
Bug fix to enable LogicValue.toRadixString(radix:10) to return a string with X or Z instead of throwing.
#542 
Tests added with X and Z in their bit values, tested to ensure a string with appropriate X or Z is returned.
No.  Throwing was not an expected behavior.
we don't have documentation on toRadixString except in code.  This will have to be included as we add more extensive documentation to the user guide:  best ways of printing LogicValue for debug.
> fix radix10 issue in toRadixString

- lib/src/signals/logic.dart
- lib/src/signals/logic_array.dart
- lib/src/signals/logic_structure.dart
- lib/src/utilities/naming.dart
- test/logic_array_test.dart
- test/logic_name_test.dart
- test/logic_structure_test.dart
The main things in this PR are:
- adding `Logic.clone`, which behaves similarly to the existing ones for `LogicStructure`
- adding `Logic.named`, which automates the creation of a named clone of a signal (usually for the purpose of making generated outputs prettier)
N/A
No
Not really, API docs cover it, maybe some general examples and guidance would be nice in the future
> Add `Logic.named` and broaden `clone`

- lib/src/simulator.dart
- test/simulator_test.dart
This PR addresses a couple problems:
- Fixes a bug (#556) where end of simulation actions were not cleared at `Simulator.reset`, causing them to get executed on the next simulation run
- Fixes a problem where the "end of simulation actions" were not executed if there was a simulator exception during the simulation.  Since there sometimes "cleanup" types of activities registered at the end, it's important not to lose those.
- Note: if a end of sim action throws an exception, other end of sim actions after it might not execute, nor the original simulator exception be thrown.  This seems reasonable.
Fix #556
Behavior will change, but this falls under "bug fix"
> Does the change require any …
> Simulator end of sim actions and exception handling

- lib/src/signals/logic_structure.dart
- test/logic_structure_test.dart
Bug in LogicStructure's withSet method where if the "update" value's width is less than the given overlapping field's width within the structure (per the start index of the set), build would crash because the out of bounds guard on the "update" value was incorrectly ignoring the "update" field's width and instead just using the overlapping field's width.
N/A
Added a single unit test to logic_structure_test that exercises the bug.
Backwards compatible.
No need for doc.
> Bug fix for withSet in LogicStructure.

- .github/workflows/general.yml
- analysis_options.yaml
- lib/src/modules/conditionals/flop.dart
- lib/src/signals/wire_net.dart
- test/async_reset_test.dart
In #533 a bug was included along with implementation of the feature allowing the `asyncReset` flag to be added to `flop` and `FlipFlop` which caused generated SystemVerilog to include an asynchronous reset, regardless of whether `asyncReset` was set to true or false.
This PR fixes the bug and adds tests which check the functionality of non-async flops to ensure they are not asynchronously triggered in either ROHD or SystemVerilog simulation.  This testing was missing in the original PR, which led to the escape.
Related to #533
Added new tests which failed without the fix
No
No
> Fix bug where non-async flop generates async flop

- lib/src/signals/logic_structure.dart
- test/logic_structure_test.dart
A typo in `LogicStructure.previousValue` caused it to actually return the *current* `value`.  This was also undertested.
This PR fixes the bug and adds a test.
N/A
Added a new test
No, bug fix
No
> Fix bug in `LogicStructure.previousValue`

- benchmark/many_seq_and_comb_benchmark.dart
- doc/tutorials/chapter_8/01_interface.md
- doc/tutorials/chapter_8/answers/exercise_1_spi.dart
- doc/tutorials/chapter_8/counter_interface.dart
- doc/tutorials/chapter_9/rohd_vf_example/lib/counter.dart
- doc/user_guide/_docs/A11-interfaces.md
- lib/src/interfaces/interface.dart
- lib/src/interfaces/pair_interface.dart
- lib/src/signals/logic.dart
- lib/src/signals/port.dart
- test/counter_wintf_test.dart
- test/interface_test.dart
- test/pair_interface_hier_test.dart
- test/pair_interface_test.dart
- test/provider_consumer_test.dart
Deprecate `Port` and replace it with a new `Logic.port` constructor with the same functionality to make the API more consistent. Other classes such as `LogicArray` and `LogicNet` already have this style of port constructor.
#506 
Updated existing tests to use `Logic.port`
No. The `Port` class is deprecated but still present.
Updated documentation to use the new `Logic.port` constructor instead of `Port`
> Deprecate `Port` and move to `Logic.port` for API consistency

- lib/src/modules/pipeline.dart
- test/pipeline_test.dart
- test/ssa_test.dart
There was a bug in ROHD `Pipeline` abstractions where when you access signals across stages (relatively or absolutely), the SSA resolution would be incorrect, causing some confusing errors.  In the end, the bug was that the abstraction was asking the `Combinational.ssa` to access signals using the `s` function even when they were actually outputs of other stages.
This PR fixes the bug in both `get` and `getAbs` and adds tests to cover the scenarios.
N/A
Added new tests to cover the issue.
The API description in `getAbs` was wrong, and the docs have been updated, so from that perspective things have changed a bit, but that's more of a documentation bug.  There's no reason you'd want to access the "output" of …
> Fix bug in cross-stage accesses in `Pipeline`

- doc/user_guide/_docs/A02-logical_signals.md
- lib/src/values/logic_value.dart
- test/logic_value_test.dart
Enable printing of leading zeros to get fixed-width output to help with alignment during printing and for parsing
from strings without having to use the size prefix, just passing the radix along with a set of strings.
#582 
Added tests that enabled the leadingZero option and checked that they match as well as not breaking existing tests.
Yes.  This option is off by default.
Yes.  An example was added to one of the user guide sections and the API for the method was updated.
> Enhance LogicValue.toRadixString to enable fixed-width output

- rohd_devtools_extension/lib/rohd_devtools/ui/module_tree_card.dart
- rohd_devtools_extension/lib/rohd_devtools/view/tree_structure_page.dart
- rohd_devtools_extension/test/modules/tree_structure/model_tree_card_test.dart
Fixed the below issues:
1. Enabled selection of module from the module tree
2. Updating the signal table with signals of the selected module from module tree
Tested it using clock_gating_example of rohd_hcl which contains two modules(gatedClk and clk_gated_counter)
Selecting particular module from the module tree and capturing if correct signals of the selected module is updated in the signal table of the UI
> Fixing selecting the module and reflecting the respective signal table
