lib/src/logic.dart
lib/src/simulator.dart
lib/src/values/logic_values.dart

add bit to LogicValues and fix injectAction bug in Simulator

---

README.md
lib/src/modules/clkgen.dart
lib/src/modules/pipeline.dart
lib/src/simulator.dart

Various documentation updates (e.g. linking to API docs in the README)
N/A
Ran `dartdoc` and reviewed output
No
Yes, it is all documentation

Documentation updates

---

example/counter.dart
lib/src/logic.dart
lib/src/simulator.dart
lib/src/utilities/simcompare.dart
test/changed_test.dart
test/wave_dumper_test.dart

Fix behavior of `Simulator.injectAction` to resolve bugs related to `Logic.changed` and others.
Fix #44 
Added new tests in changed_test.dart
No
No

Fixed injection behavior and added some testing for changed events

---

lib/src/logic.dart
lib/src/module.dart
lib/src/modules/bus.dart
lib/src/modules/clkgen.dart
lib/src/modules/conditional.dart
lib/src/modules/gates.dart
lib/src/modules/pipeline.dart
lib/src/simulator.dart
lib/src/synthesizers/systemverilog.dart
lib/src/utilities/uniquifier.dart
lib/src/values/logic_value.dart
lib/src/values/logic_values.dart
lib/src/wave_dumper.dart
test/bus_test.dart
test/comparison_test.dart

Improving the messages for various Exceptions and errors.
Close #64 
Existing test suite
No
No

Improve exception and error messaging

---

test/logic_values_test.dart

Wanted to clean up logic_values_test.dart that I changed in previous pull request.  I noticed two TODOs and wanted to follow through on them.
AFAIK, none
These are changes in tests, so not exactly applicable.
Not applicable; changed only tests
Not applicable; changed only tests

Improve logicValues testing, fixing todos

---

lib/src/interface.dart

Adjusts the behavior and API for `Interface`.  The original API made it difficult to extract and/or differentiate between `Interface` port names and `Logic` signal names associated with an `Interface`.  The port name on an `Interface` doesn't change when signal names are uniquified, which can cause some confusion and difficulty.  The updated APIs make it more clear and easier to extract the desired information, particularly when automating connections of interfaces.
Also fixed a subtle but in `setPort` related to uniquified ports.
N/A
Existing test suite passes
Yes!
- `setPort` is now a private function
- `getPorts` returns a Map from port names to `Logic` signals instead of just a `List<Logic>`
> Does the …

Adjustments to `Interface`

---

example/fir_filter.dart
test/example_test.dart

I would like to add an example to demonstrate the ROHD can also act like generator.
This example is based on the Chisel example
Don't forget to **rebase and merge** my commits.
NA
This example only do the build check and added in example_test.dart
NO
No

Added a FIR filter example

---

CONTRIBUTING.md
README.md

Add information and invite links about the Discord server.
N/A
N/A
No
Yes, that's all it is!

Add Discord server information

---

CODE_OF_CONDUCT.md

Updating contributor covenant code of conduct to newer version
Fix #182 
Doc only
No
No

Update to contributor covenant v2.1 (fix #182)

---

doc/TreeExample.md

Thank you @eric-norige for noticing that the tree example was a little out of date.  This PR updates it.
N/A
N/A, doc changes only
No
Only doc

Fix the tree example doc

---

CONTRIBUTING.md
README.md
doc/Architecture.md
security.md

There are a handful of documentation updates needed, and this PR adds them.
N/A
Docs only
No
Docs only

Updates to some documentation

---

tool/gh_actions/check_documentation.sh

Fix documentation check (see https://github.com/intel/rohd-vf/pull/35)
N/A
Ran script locally, CI/CD will double-check it
No
No

Fix doc check

---

tool/generate_coverage.sh

Add branch coverage to the generate_coverage script for additional insight.
N/A
Ran locally
(found that function coverage hangs, so not included)
No
No

Add branch coverage to script

---

benchmark/many_seq_and_comb_benchmark.dart
test/ssa_test.dart

Some tests were failing upon changes that shouldn't have caused them to fail (#393).  This fixes those tests to be more robust to changes.  The tests still cover the important parts.
N/A
Only tests changed.
No
No

Fix some sensitive tests to be more robust

---

.github/workflows/build_devtool.yml
.github/workflows/general.yml

Fix the build fail on flutter devtool extension.
NA
Tested on forked main branch.
no
no

fix: update flutter version to the latest

---

.gitignore
.pubignore
CHANGELOG.md
lib/src/utilities/config.dart
pubspec.yaml

Preparations to release v0.6.0 of ROHD

Preparing to release v0.6.0

---

CHANGELOG.md
README.md
lib/src/utilities/config.dart
pubspec.yaml

Preparations to release v0.6.1 of ROHD

Preparing to release v0.6.1

---

CHANGELOG.md
lib/src/simulator.dart
lib/src/utilities/config.dart
pubspec.yaml

Preparations to release v0.6.2 of ROHD

Preparing to release v0.6.2

---

CHANGELOG.md
lib/src/utilities/config.dart
pubspec.yaml

Preparations to release v0.6.3 of ROHD

Preparing to release v0.6.3

---

CHANGELOG.md
lib/src/utilities/config.dart
pubspec.yaml

Preparations to release v0.6.4 of ROHD

Preparing to release v0.6.4

---

CHANGELOG.md
lib/src/utilities/config.dart
pubspec.yaml

Preparing to release v0.6.5

---

.github/workflows/general.yml
CHANGELOG.md
lib/src/utilities/config.dart
pubspec.yaml

Preparing to release v0.6.6
